### ISSUE TITLE
interface conversion: *webutil.StatusResponseWriter is not http.Hijacker: missing method Hijack

### ISSUE THREAD

**Issue by adg** [lkesteloot/trs80emu#2]
Just installed with `go get -u` and when I run `trs80` from the repo root I get this error message:

```
2014/09/09 10:35:06 http: panic serving [::1]:56868: interface conversion: *webutil.StatusResponseWriter is not http.Hijacker: missing method Hijack
goroutine 12 [running]:
net/http.func·011()
    /Users/adg/go/src/net/http/server.go:1100 +0xba fp=0xc2080c98b0 sp=0xc2080c97e0
runtime.call16(0xc2080c9ec0, 0xc208029978, 0x0)
    /Users/adg/go/src/runtime/asm_amd64.s:390 +0x44 fp=0xc2080c98c8 sp=0xc2080c98b0
runtime.gopanic(0x326420, 0xc2080308c0)
    /Users/adg/go/src/runtime/panic1.go:60 +0x1be fp=0xc2080c9970 sp=0xc2080c98c8
runtime.getitab(0x3087e0, 0x3453e0, 0x0, 0x34ae00)
    /Users/adg/go/src/runtime/iface.go:110 +0x447 fp=0xc2080c99c8 sp=0xc2080c9970
runtime.assertI2I(0x3087e0, 0x67a800, 0xc20804f180, 0x0, 0x0)
    /Users/adg/go/src/runtime/iface.go:328 +0x12b fp=0xc2080c9a00 sp=0xc2080c99c8
code.google.com/p/go.net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x420c70, ...)
    /Users/adg/src/code.google.com/p/go.net/websocket/server.go:74 +0x7a fp=0xc2080c9ab0 sp=0xc2080c9a00
code.google.com/p/go.net/websocket.Handler.ServeHTTP(0x424ac8, 0x67a800, 0xc20804f180, 0xc208001450)
    /Users/adg/src/code.google.com/p/go.net/websocket/server.go:113 +0x94 fp=0xc2080c9b80 sp=0xc2080c9ab0
net/http.(*ServeMux).ServeHTTP(0xc208028c00, 0x67a800, 0xc20804f180, 0xc208001450)
    /Users/adg/go/src/net/http/server.go:1511 +0x17c fp=0xc2080c9bd8 sp=0xc2080c9b80
github.com/lkesteloot/goutil/webutil.func·003(0x67a7c8, 0xc20805a640, 0xc208001450)
    /Users/adg/src/github.com/lkesteloot/goutil/webutil/logging.go:48 +0x149 fp=0xc2080c9c70 sp=0xc2080c9bd8
net/http.HandlerFunc.ServeHTTP(0xc20800ca50, 0x67a7c8, 0xc20805a640, 0xc208001450)
    /Users/adg/go/src/net/http/server.go:1235 +0x40 fp=0xc2080c9c90 sp=0xc2080c9c70
net/http.serverHandler.ServeHTTP(0xc2080580c0, 0x67a7c8, 0xc20805a640, 0xc208001450)
    /Users/adg/go/src/net/http/server.go:1673 +0x1a4 fp=0xc2080c9ce8 sp=0xc2080c9c90
net/http.(*conn).serve(0xc2080a2900)
    /Users/adg/go/src/net/http/server.go:1174 +0xa81 fp=0xc2080c9fa8 sp=0xc2080c9ce8
runtime.goexit()
    /Users/adg/go/src/runtime/proc.c:1771 fp=0xc2080c9fb0 sp=0xc2080c9fa8
created by net/http.(*Server).Serve
    /Users/adg/go/src/net/http/server.go:1721 +0x316
```

Any idea why?

**Comment by lkesteloot** [comment]
Looks like the new version of Go assumes that the HTTP writer implements the Hijack interface. I've updated my utility library. If you update it:

```
go get -u github.com/lkesteloot/goutil/webutil
```

It should get past that point. It still fails a few seconds later because of a websocket error. Must be another change in Go. I'll investigate.

**Comment by lkesteloot** [comment]
Okay other problem (socket timeout) solved too. Do a "go get -u" on the trs80 package to get the fixes. Thanks for reporting the problem!

**Comment by adg** [comment]
Cool, it works! Very nice. Brings back memories.
